//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __myfileoutput_base_h__
#define __myfileoutput_base_h__

// Includes
#include <wx/button.h>
#include <wx/stattext.h>
#include <wx/filepicker.h>
#include <wx/xrc/xmlres.h>

class MyFileOutput_Base : public wxDialog {
protected:
 wxStaticText* m_FileOutputNameStaticText;
 wxDirPickerCtrl* m_FileOutputNameDirPicker;
 wxButton* wxID_FileOutputOK;
 wxButton* wxID_FileOutputCANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MyFileOutput_Base"), wxT("wxDialog"));
  m_FileOutputNameStaticText = XRCCTRL(*this,"m_FileOutputNameStaticText",wxStaticText);
  m_FileOutputNameDirPicker = XRCCTRL(*this,"m_FileOutputNameDirPicker",wxDirPickerCtrl);
  wxID_FileOutputOK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_FileOutputCANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
MyFileOutput_Base(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void InitXmlResource();
#endif
