//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __myfileoutput_base_h__
#define __myfileoutput_base_h__

#include <wx/xrc/xmlres.h>
#include <wx/stattext.h>
#include <wx/filepicker.h>
#include <wx/button.h>

class MyFileOutput_Base : public wxDialog {
protected:
 wxStaticText* m_FileOutputNameStaticText;
 wxFilePickerCtrl* m_FileOutputNameFilePicker;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MyFileOutput_Base"), wxT("wxDialog"));
  m_FileOutputNameStaticText = XRCCTRL(*this,"m_FileOutputNameStaticText",wxStaticText);
  m_FileOutputNameFilePicker = XRCCTRL(*this,"m_FileOutputNameFilePicker",wxFilePickerCtrl);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
MyFileOutput_Base(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlResource();
#endif
