//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __myports_base_h__
#define __myports_base_h__

// Includes
#include <wx/stattext.h>
#include <wx/choice.h>
#include <wx/button.h>
#include <wx/xrc/xmlres.h>

class MyPorts_Base : public wxDialog {
protected:
 wxStaticText* m_PortsMotor1StaticText;
 wxChoice* m_PortsMotor1Choice;
 wxStaticText* m_PortsMotor2StaticText;
 wxChoice* m_PortsMotor2Choice;
 wxStaticText* m_PortsForceStaticText;
 wxChoice* m_PortsForceChoice;
 wxButton* wxID_PortsOK;
 wxButton* wxID_PortsCANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MyPorts_Base"), wxT("wxDialog"));
  m_PortsMotor1StaticText = XRCCTRL(*this,"m_PortsMotor1StaticText",wxStaticText);
  m_PortsMotor1Choice = XRCCTRL(*this,"m_PortsMotor1Choice",wxChoice);
  m_PortsMotor2StaticText = XRCCTRL(*this,"m_PortsMotor2StaticText",wxStaticText);
  m_PortsMotor2Choice = XRCCTRL(*this,"m_PortsMotor2Choice",wxChoice);
  m_PortsForceStaticText = XRCCTRL(*this,"m_PortsForceStaticText",wxStaticText);
  m_PortsForceChoice = XRCCTRL(*this,"m_PortsForceChoice",wxChoice);
  wxID_PortsOK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_PortsCANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
MyPorts_Base(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlResource();
#endif
