//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __resource_h__
#define __resource_h__

#include <wx/frame.h>
#include <wx/notebook.h>
#include <wx/xrc/xmlres.h>

class MyFrame_Base : public wxFrame {
protected:
 wxNotebook* m_Experiments;
 wxPanel* m_InitializePanel;
 wxPanel* m_ClampingPosPanel;
 wxPanel* m_PreloadPanel;
 wxPanel* m_Ramp2FailurePanel;
 wxPanel* m_RelaxationPanel;
 wxPanel* m_CreepPanel;
 wxPanel* m_FatiguePanel;
 wxPanel* m_Protocols;
 wxScrolledWindow* m_Results;

//private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MyFrame_Base"), wxT("wxFrame"));
  m_Experiments = XRCCTRL(*this,"m_Experiments",wxNotebook);
  m_InitializePanel = XRCCTRL(*this,"m_InitializePanel",wxPanel);
  m_ClampingPosPanel = XRCCTRL(*this,"m_ClampingPosPanel",wxPanel);
  m_PreloadPanel = XRCCTRL(*this,"m_PreloadPanel",wxPanel);
  m_Ramp2FailurePanel = XRCCTRL(*this,"m_Ramp2FailurePanel",wxPanel);
  m_RelaxationPanel = XRCCTRL(*this,"m_RelaxationPanel",wxPanel);
  m_CreepPanel = XRCCTRL(*this,"m_CreepPanel",wxPanel);
  m_FatiguePanel = XRCCTRL(*this,"m_FatiguePanel",wxPanel);
  m_Protocols = XRCCTRL(*this,"m_Protocols",wxPanel);
  m_Results = XRCCTRL(*this,"m_Results",wxScrolledWindow);
 }
public:
MyFrame_Base(const wxString& title, wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void InitXmlResource();
#endif
